### ISSUE TITLE
Couldn't run hiddify-next as root

### ISSUE THREAD

**Issue by NotMephisto** [hiddify/hiddify-app#1434]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

It is not possible to run the program from sudo permission to use vpn mode.

### Minimal Reproducible Example (MRE)

1. Try launch app from terminal with this commands (pkexec hiddify %U | sudo hiddify)
2. Got in terminal output "cannot open display: :0"

### Version

2.5.7

### Platform/OS

Linux

### Additional Context

OS: Fedora 40
DE: Hyrpland
Kernel: 6.11.4

### Application Config Options

```shell
{
  "region": "ru",
  "block-ads": false,
  "use-xray-core-when-possible": false,
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 12334,
  "tproxy-port": 12335,
  "local-dns-port": 16450,
  "tun-implementation": "gvisor",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 16756,
  "enable-tun": true,
  "enable-tun-service": false,
  "set-system-proxy": false,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "rules": [],
  "mux": {
    "enable": false,
    "padding": false,
    "max-streams": 8,
    "protocol": "h2mux"
  },
  "tls-tricks": {
    "enable-fragment": false,
    "fragment-size": "10-30",
    "fragment-sleep": "2-8",
    "mixed-sni-case": false,
    "enable-padding": false,
    "padding-size": "1-1500"
  },
  "warp": {
    "enable": false,
    "mode": "proxy_over_warp",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m4"
  },
  "warp2": {
    "enable": false,
    "mode": "proxy_over_warp",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m4"
  }
}
```

### Relevant log output

```shell
➜  ~ pkexec hiddify %U

(hiddify:749263): Gtk-WARNING **: 15:19:49.808: cannot open display: 
➜  ~ sudo hiddify     
Authorization required, but no authorization protocol specified


(hiddify:749760): Gtk-WARNING **: 15:22:59.766: cannot open display: :0
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lufog** [comment]
This is not `hiddify` problem. From the `pkexec` man.

>The environment that PROGRAM will run in will be set to a minimal known and safe environment in order to avoid injecting code through LD_LIBRARY_PATH or similar mechanisms. In addition the PKEXEC_UID environment variable is set to the user id of the process invoking pkexec.

You can cause `pkexec` to retain some environmental variables for GUI programs to work
```
pkexec env DISPLAY=$DISPLAY WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_SESSION_TYPE=$XDG_SESSION_TYPE XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR hiddify
``` 
I use `sudo -E hiddify` to make the program load settings from the current user's home directory instead of `/root/`.

**Comment by NotMephisto** [comment]
> This is not `hiddify` problem. From the `pkexec` man.
> 
> > The environment that PROGRAM will run in will be set to a minimal known and safe environment in order to avoid injecting code through LD_LIBRARY_PATH or similar mechanisms. In addition the PKEXEC_UID environment variable is set to the user id of the process invoking pkexec.
> 
> You can cause `pkexec` to retain some environmental variables for GUI programs to work
> 
> ```
> pkexec env DISPLAY=$DISPLAY WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_SESSION_TYPE=$XDG_SESSION_TYPE XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR hiddify
> ```
> 
> I use `sudo -E hiddify` to make the program load settings from the current user's home directory instead of `/root/`. To get similar behavior for `pkexec` you can add `HOME=$HOME`.

You're right, I checked it and it's works by adding `-E`  variable 

But I don't get it, why hiddify doesn't launch with root settings? Maybe I should figured out what causes this issue

**Comment by lufog** [comment]
> But I don't get it, why hiddify doesn't launch with root settings? Maybe I should figured out what causes this issue

Because it (like many GUI applications) requires certain environment variables. And `sudo -E` preserves user environment.
```
-E, --preserve-env            preserve user environment when running command
```

Running GUI applications as root is generally bad practice. Because it is too big an attack vector (source of vulnerabilities). I hope that this is a temporary solution, and in the future the program will add more fine-grained control of privilege escalation using `polkit`.

**Comment by TheHanza** [comment]
this works for me:
https://chatgpt.com/s/t_689dc7a8fc588191a93c594a4d00a979
