### ISSUE TITLE
crash ios version when warp option is open

### ISSUE THREAD

**Issue by Utra1377** [hiddify/hiddify-app#1462]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

سلام وقت بخیر
خیلی ممنون بابت زحماتتون و تلاش های بی دریغتون
در ورژن آی او اس وقتی گزینه وارپ فعاله برنامه کرش میکنه و همچنین در صورت امکان مثل نسخه تست فلایت گزینه اضافه کردن خودکار وارپ رو هم اضافه کنین
همیشه موفق باشین و با قدرت ادامه بدین

### Minimal Reproducible Example (MRE)

1.go to setting
2. scroll down
3. warp

### Version

v2.7

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by splendidx** [comment]
Me too encountered this problem while downloading the ios version fisrt time ，f*ck！ Nobody had ever tried to fix it？
