### ISSUE TITLE
conneection test url

### ISSUE THREAD

**Issue by mobohes** [hiddify/hiddify-app#1477]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The conneection test urll should be changed and default to http://1.1.1.1 so that it can be connected to all internets in Iran and there is no problem in displaying ping.

### Minimal Reproducible Example (MRE)

1. Go misc options
2. Conneection Test URL
3. default be http://1.1.1.1

### Version

v2.5.7

### Platform/OS

Android, Windows, iOS

### Additional Context

![image](https://github.com/user-attachments/assets/c647455e-64ab-4e10-92d8-ef757783c0cb)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
1.1.1.1
will not work with worker and also not work in china
