### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by IMMOBINIUM** [hiddify/hiddify-app#1491]
## BlackScreen 

I was using version 1.6.dev and everything was ok, when I install new versions, they are all black.

i tried everything, install from microsoft store or install with official setup
not working...
please help me 

![{9242ACAB-B5AF-4E51-825D-F8AB1E236114}](https://github.com/user-attachments/assets/dd0ee2cc-c102-44c4-b44f-d2faabc30f95)

**Comment by lufog** [comment]
Cause: https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2411878488

Temporary workaround: https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601
