### ISSUE TITLE
[FR] The portable version of the software reads the configuration in the data folder of the current directory of the executable by default.

### ISSUE THREAD

**Issue by lanceyliao** [hiddify/hiddify-app#397]
### Feature description

Because there are scenarios where multiple computers synchronize all their files via a cloud drive (e.g. onedrive).

Similar to what Clash for Windows does:
Version Requirements
Starting from version 0.13.1, the way to open Portable Mode is simply adjusted, refer to the way to open the old version for reference

#How to open Portable Mode
When a new folder named data is created in the current directory of the software executable, Portable Mode will use this folder as the base startup folder and as the Home Directory.

The location of the executable varies on different systems:

Windows: Clash for Windows.exe in the installation directory
macOS: /Contents/MacOS/Clash for Windows in the package directory
When the folder exists, restart the software to enter portable mode, and the software will read/write data to this directory.

Translated with www.DeepL.com/Translator (free version)
![image](https://github.com/hiddify/hiddify-next/assets/45159389/be54c530-1a48-42c6-a1ce-ec66b5b9c7ea)
![image](https://github.com/hiddify/hiddify-next/assets/45159389/a59b836c-4a6c-4067-8853-587d6ce3c9cf)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.

**Comment by Joackk** [comment]
Is this feature already available? How do I open it

**Comment by lanceyliao** [comment]
> Is this feature already available? How do I open it

I've switched to using clash verge.

**Comment by Joackk** [comment]
> > Is this feature already available? How do I open it
> 
> I've switched to using clash verge.

I always felt like the clash verge was a little slower

**Comment by eXense-auth** [comment]
Here's a portable version.
https://github.com/xmha97/PortableApps/releases?q=Hiddify
You can put any version you want into the container
